version: '3'

networks:
  patch-api:

volumes:
  db_data: {}
  redis_data: {}

services:
  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./nginx
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - patch-api
    depends_on:
      - php-1
      - php-2

  php-1:
    container_name: php-1
    restart: on-failure
    build:
      context: ./php
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app/public
    depends_on:
      - mysql
      - redis
    expose:
      - "9000"
    networks:
      - patch-api
    command: ["php-fpm","-R"]

  php-2:
    container_name: php-2
    restart: on-failure
    build:
      context: ./php
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app/public
    depends_on:
      - mysql
      - redis
    expose:
      - "9000"
    networks:
      - patch-api
    command: ["php-fpm","-R"]

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: patch-api-db
      MYSQL_USER: patch-api-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"
    networks:
      - patch-api

  redis:
    image: redis:6.0-alpine
    container_name: redis
    restart: on-failure
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - patch-api

  horizon-worker:
    build:
      context: ./horizon-worker
    container_name: horizon-worker
    restart: on-failure
    depends_on:
      - mysql
      - redis
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app
    networks:
      - patch-api
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-u", "root", "-j", "/supervisord.pid", "-l", "/horizon-worker.log"]

#  worker:
#    build:
#      context: ./worker
#    container_name: worker
#    restart: on-failure
#    depends_on:
#      - mysql
#      - redis
#    volumes:
#      - ${LOCAL_PROJECT_PATH}:/app
#    working_dir: /app
#    networks:
#      - patch-api
#    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-u", "root", "-j", "/supervisord.pid", "-l", "/worker.log"]

  scheduler:
    build:
      context: ./scheduler
    container_name: scheduler
    restart: on-failure
    depends_on:
      - mysql
      - redis
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app
    networks:
      - patch-api
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-u", "root", "-j", "/supervisord.pid", "-l", "/scheduler.log"]