version: '3'

networks:
  patch-api:

volumes:
  db_data: {}

services:
  nginx:
    container_name: nginx
    tty: false
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - patch-api
    depends_on:
      - php

  php:
    container_name: php
    tty: true
    restart: always
    build:
      context: ./php
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app/public
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    networks:
      - patch-api
    command: ["php-fpm","-R"]

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: false
    environment:
      MYSQL_DATABASE: patch-api-db
      MYSQL_USER: patch-api-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - patch-api

  redis:
    image: redis:6.0-alpine
    container_name: redis
    restart: always
    tty: false
    ports:
      - "6379"
    networks:
      - patch-api

  worker:
    build:
      context: ./worker
    container_name: worker
    tty: true
    depends_on:
      - mysql
      - redis
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app
    networks:
      - patch-api
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-u", "root", "-j", "/supervisord.pid", "-l", "/worker.log"]

  scheduler:
    build:
      context: ./scheduler
    container_name: scheduler
    tty: true
    depends_on:
      - mysql
      - redis
    volumes:
      - ${LOCAL_PROJECT_PATH}:/app
    working_dir: /app
    networks:
      - patch-api
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-u", "root", "-j", "/supervisord.pid", "-l", "/scheduler.log"]